### PR TITLE
cleaned the randomsimple search module, using z3 to get feasible points

### PR DESCRIPTION
**Pull request by coti**
Simple, random search module that uses z3.

### CODE REVIEW

**Comment by brnorris03** [comment]
Shouldn't the z3 class be in the main search module (not in randomsimple?) -- ideally we'd like to use it in most modules without replicating it.

**Comment by coti** [comment]
This was the initial approach, but you asked me to put everything in the modules (even if it involved replicating) instead.

**Comment by brnorris03** [comment]
> This was the initial approach, but you asked me to put everything in the modules (even if it involved replicating) instead.

That was because I thought it was part of the new search method, and not reusable. Now I understand it better, so it should be available to all.

**Comment by coti** [comment]
Ok, I will prepare that.

**Pull request closed without merging**
